import type { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'SmartSphere X1',
    description: 'The latest innovation in smart home technology, offering seamless integration and intuitive control over your connected devices. Features voice assistance and energy monitoring.',
    price: 129.99,
    imageUrl: 'https://images.unsplash.com/photo-1746960875630-64b3e3d3c4d9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    dataAiHint: 'smart home',
    category: 'Electronics',
    stock: 15,
    rating: 4.8,
    reviews: 120,
  },
  {
    id: '2',
    name: 'AeroGlide Sneakers',
    description: 'Experience ultimate comfort and style with AeroGlide sneakers. Engineered for performance and designed for everyday wear. Lightweight, breathable, and durable.',
    price: 89.50,
    imageUrl: 'https://images.unsplash.com/photo-1746960875630-64b3e3d3c4d9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    dataAiHint: 'running shoes',
    category: 'Apparel',
    stock: 30,
    rating: 4.5,
    reviews: 85,
  },
  {
    id: '3',
    name: 'LuxeComfort Throw Blanket',
    description: 'Wrap yourself in luxury with this ultra-soft throw blanket. Perfect for cozy evenings, adding a touch of elegance to any room. Machine washable.',
    price: 49.99,
    imageUrl: 'https://images.unsplash.com/photo-1746960875630-64b3e3d3c4d9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    dataAiHint: 'home decor',
    category: 'Home Goods',
    stock: 22,
    rating: 4.9,
    reviews: 210,
  },
  {
    id: '4',
    name: 'QuantumCode: The Algorithmic Mind',
    description: 'A captivating journey into the world of algorithms and artificial intelligence. This book explores the future of technology and its impact on society.',
    price: 24.95,
    imageUrl: 'https://images.unsplash.com/photo-1746960875630-64b3e3d3c4d9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    dataAiHint: 'technology book',
    category: 'Books',
    stock: 50,
    rating: 4.7,
    reviews: 65,
  },
  {
    id: '5',
    name: 'ProBlend Mixer',
    description: 'Powerful and versatile, the ProBlend Mixer makes kitchen tasks a breeze. From smoothies to soups, achieve perfect consistency every time. Multiple speed settings.',
    price: 75.00,
    imageUrl: 'https://images.unsplash.com/photo-1746960875630-64b3e3d3c4d9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    dataAiHint: 'kitchen appliance',
    category: 'Home Goods',
    stock: 18,
    rating: 4.6,
    reviews: 92,
  },
  {
    id: '6',
    name: 'Nova Wireless Earbuds',
    description: 'Immerse yourself in crystal-clear audio with Nova Wireless Earbuds. Featuring noise cancellation, long battery life, and a comfortable, secure fit.',
    price: 110.00,
    imageUrl: 'https://images.unsplash.com/photo-1746960875630-64b3e3d3c4d9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    dataAiHint: 'audio headphones',
    category: 'Electronics',
    stock: 25,
    rating: 4.4,
    reviews: 150,
  },
  {
    id: '7',
    name: 'Urban Explorer Backpack',
    description: 'Durable and stylish backpack designed for the modern adventurer. Multiple compartments, water-resistant material, and ergonomic design for comfort.',
    price: 65.99,
    imageUrl: 'https://images.unsplash.com/photo-1746960875630-64b3e3d3c4d9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    dataAiHint: 'travel gear',
    category: 'Apparel',
    stock: 40,
    rating: 4.7,
    reviews: 77,
  },
  {
    id: '8',
    name: 'The StarGazer\'s Almanac',
    description: 'An essential guide for amateur astronomers. Detailed star charts, celestial event calendars, and tips for observing the night sky. Beautifully illustrated.',
    price: 19.99,
    imageUrl: 'https://images.unsplash.com/photo-1746960875630-64b3e3d3c4d9?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    dataAiHint: 'science book',
    category: 'Books',
    stock: 35,
    rating: 4.9,
    reviews: 50,
  },
];
